[build]
functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src *; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"
